language: java

cache:
  directories:
  - $HOME/arcus 
  - $HOME/.m2

before_install:
  - sudo apt-get install -qq build-essential autoconf automake libtool libcppunit-dev python-setuptools python-dev ant
  - bash TARGET_CLIENT_BRANCH=`git name-rev --name-only HEAD`
  - bash install-arcus-memcached.sh $TARGET_CLIENT_BRANCH

script:
  - mvn test -DUSE_ZK=false && mvn test -DUSE_ZK=true

notifications:
  email:
    - alsdn653@jam2in.com
