language: java

cache:
  directories:
  - $HOME/arcus 
  - $HOME/.m2

before_install:
  - sudo apt-get install -qq build-essential autoconf automake libtool libcppunit-dev python-setuptools python-dev ant
  - bash install-arcus-memcached.sh develop

script:
  - mvn test -DUSE_ZK=false

notifications:
  email:
    - alsdn653@jam2in.com
